services:
 api:
  build: .
  container_name: acquisitions-api
  restart: unless-stopped
  ports:
    - "3000:3000"
  env_file:
    - .env
  
#  db:
#   image: postgres:15-alpine
#   container_name: acquisitions-db
#   restart: unless-stopped
#   environment:
#    POSTGRES_USER: ${DB_USER}
#    POSTGRES_PASSWORD: ${DB_PASSWORD}
#    POSTGRES_DB: ${DB_NAME}
#   volumes:
#     - db_data:/var/lib/postgresql/data
#   ports:
#     - "5432:5432"

# volumes:
#   db_data:
